import { Modal, View, Text, TouchableOpacity, ScrollView, StyleSheet, Linking, Alert } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { ParentAlert } from '../../hooks/use-parent-alerts';
type Props = { kind: 'children' | 'notifications' | 'contact' | null; onClose: () => void; children: any[]; selectedId?: string; onChild: (id: string) => void; driver: any; notifications: ParentAlert[]; error: string; onRefresh: () => void; onRead: () => void };
export default function ParentDialogs(p: Props) {
  return <Modal visible={!!p.kind} transparent animationType="fade" onRequestClose={p.onClose}>
    <View style={styles.overlay}><View style={styles.dialog}>
      <View style={styles.header}><Text style={styles.title}>{p.kind === 'children' ? 'Choose your child' : p.kind === 'notifications' ? 'Notifications' : 'Contact Driver'}</Text><TouchableOpacity accessibilityLabel="Close" onPress={p.onClose}><Ionicons name="close" size={25} color="#172554" /></TouchableOpacity></View>
      {p.kind === 'children' && <ScrollView>{p.children.map(child => <TouchableOpacity accessibilityRole="button" key={child._id} style={styles.row} onPress={() => { p.onChild(child._id); p.onClose(); }}><Ionicons name="person-circle" size={32} color="#1683f7" /><View style={styles.flex}><Text style={styles.bold}>{child.name}</Text><Text style={styles.small}>{child.class ? `Class ${child.class}` : 'Student'}</Text></View>{child._id === p.selectedId && <Ionicons name="checkmark-circle" size={24} color="#00ab5b" />}</TouchableOpacity>)}</ScrollView>}
      {p.kind === 'notifications' && <><View style={styles.header}><TouchableOpacity onPress={p.onRefresh}><Text style={styles.link}>Refresh</Text></TouchableOpacity><TouchableOpacity onPress={p.onRead}><Text style={styles.link}>Mark shown alerts read</Text></TouchableOpacity></View>{!!p.error && <Text style={styles.error}>{p.error}</Text>}<ScrollView>{!p.notifications.length && <Text style={styles.small}>No trip alerts yet. New alerts will appear here.</Text>}{p.notifications.map(n => <View key={n._id} style={[styles.alert, !n.readAt && styles.unread]}><Text style={styles.bold}>{n.title}{!n.readAt ? ' • New' : ''}</Text><Text style={styles.body}>{n.message}</Text><Text style={styles.small}>{new Date(n.createdAt).toLocaleString()}</Text></View>)}</ScrollView></>}
      {p.kind === 'contact' && <><Text style={styles.bold}>{p.driver?.fullName || 'Driver not assigned'}</Text><Text style={styles.body}>{p.driver?.phone || 'Contact number unavailable. Please ask your driver or school to update it.'}</Text>{!!p.driver?.phone && <TouchableOpacity style={styles.call} onPress={async () => { try { await Linking.openURL(`tel:${p.driver.phone}`); } catch { Alert.alert('Could not open dialler', `Call ${p.driver.phone} from your phone.`); } }}><Ionicons name="call" size={20} color="#fff" /><Text style={styles.callText}>Call Driver</Text></TouchableOpacity>}</>}
    </View></View>
  </Modal>;
}
const styles = StyleSheet.create({ overlay: { flex: 1, backgroundColor: '#0f172a80', justifyContent: 'center', padding: 20 }, dialog: { backgroundColor: '#fff', borderRadius: 20, padding: 20, maxHeight: '80%' }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }, title: { color: '#172554', fontSize: 20, fontWeight: '800' }, row: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 14 }, flex: { flex: 1 }, bold: { color: '#172554', fontSize: 15, fontWeight: '700' }, small: { color: '#64748b', fontSize: 12, marginTop: 5 }, body: { color: '#475569', fontSize: 14, lineHeight: 21, marginVertical: 8 }, link: { color: '#087cf0', fontWeight: '700', fontSize: 12 }, error: { color: '#b91c1c', marginBottom: 10 }, alert: { padding: 12, borderRadius: 12, marginBottom: 10, backgroundColor: '#f8fafc' }, unread: { backgroundColor: '#edf7ff' }, call: { backgroundColor: '#00ab5b', flexDirection: 'row', justifyContent: 'center', gap: 10, padding: 14, borderRadius: 12 }, callText: { color: '#fff', fontWeight: '700' } });
